name: Download YouTube Video (Best Quality + Cookies)

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "YouTube URL (e.g., https://youtu.be/fpXW6nZC7WE)"
        required: true
        default: "https://youtu.be/fpXW6nZC7WE"

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo snap install ffmpeg  # Faster than apt-get
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Download using cookies.json
        run: |
          # Download with cookies in best quality format
          yt-dlp \
            --cookies cookies.json \
            -f "best" \
            --merge-output-format mp4 \
            --ffmpeg-location /snap/bin/ffmpeg \
            -o "%(title)s.%(ext)s" \
            "${{ github.event.inputs.youtube_url}}"
          
          # Optional: FFmpeg post-processing example (convert to 1080p)
          ffmpeg -i *.mp4 -vf "scale=1920:1080" -c:a copy output_1080p.mp4

      - name: Upload downloaded files
        uses: actions/upload-artifact@v4
        with:
          name: youtube-downloads
          path: |
            *.mp4
            *.mkv
            output_1080p.mp4
